site_name: Maratona de Programação - Instituto de Informática - UFG
site_url: https://mydomain.org/mysite

nav:
  - Início: 'index.md'
  - Notícias: 
      - 'blog/index.md'
  - Resultados: 'results.md'
  - Programação: 'schedule.md'
  - Inscrição: 'subscription.md'
  - Organização: 'organization.md'
  - Contato: 'contact.md'
  - Fale Conosco: 'support.md'
  - Portal do INF: 'portal.md'

theme:
  language: pt-BR
  name: material
  logo: assets/transparent_logo.png
  favicon: assets/favicon.ico
  icon:
    annotation: material/arrow-right-circle
    repo: fontawesome/brands/github
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: blue
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep blue
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.indexes
    - content.code.copy
    - content.code.select
    - content.tooltips

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - abbr
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - tables
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - pymdownx.arithmatex:
      generic: true
repo_url: https://github.com/Monkeys-UFG/maratonago
repo_name: Monkeys-UFG/maratonago

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Monkeys-UFG/
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/ufg_monkeys
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/ufg_monkeys

plugins:
  - search
  - glightbox
  - git-revision-date-localized:
      enable_creation_date: true
      enabled: true
      locale: pt
  - git-committers:
      repository: Monkeys-UFG/maratonago
      branch: main
      enabled: true
  - blog:
      blog_dir: blog
      categories_allowed:
        - Contests
        - test
      post_url_format: "{slug}"

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/slider.js

extra_css:
  - stylesheets/extra.css
  - stylesheets/slider.css